from pathlib import Path


def test_performance_baseline_script_contains_required_contract():
    repo_root = Path(__file__).resolve().parents[2]
    script_path = repo_root / "scripts" / "run_performance_baseline.ps1"
    content = script_path.read_text(encoding="utf-8")

    required_tokens = [
        "param(",
        "[switch]$FailOnWarn",
        "[string]$ApiBaseUrl",
        "[string]$FrontendUrl",
        "[string]$OutputPath",
        "[switch]$SkipBackendSmoke",
        "[switch]$SkipFrontendSmoke",
        "[int]$Iterations = 10",
        "[string]$BusinessPaths",
        "[string]$BusinessHeadersJson",
        "[string]$BusinessAuthorization",
        "[string]$BusinessUserId",
        "[string]$BusinessTenantId",
        "[string]$BusinessRoles",
        "PERF_BASELINE_BUSINESS_HEADERS_JSON",
        "PERF_BASELINE_AUTHORIZATION",
        "PERF_BASELINE_USER_ID",
        "PERF_BASELINE_TENANT_ID",
        "Get-BusinessRequestHeaders",
        "[string]$TrendPath",
        "Invoke-WebRequest",
        "/health",
        "meanMs",
        "minMs",
        "p50Ms",
        "p90Ms",
        "p95Ms",
        "maxMs",
        "errorCount",
        "timeoutCount",
        "successRatePct",
        "errorRatePct",
        "generatedAt",
        "targets",
        "businessTargets",
        "businessAuthMode",
        "results",
        "summary",
        "business",
        "trend",
        "latest",
        "comparison",
        "regressionCount",
        "p95DeltaMs",
        "errorCountDelta",
        "thresholds",
        "conclusion",
        "gate",
        "failOnWarn",
        "shouldFail",
        "exitCode",
        "$backendThresholdP95Ms = 1000",
        "$frontendThresholdP95Ms = 2000",
        "Get-DingTalkSignedWebhookUrl",
        "[System.Security.Cryptography.HMACSHA256]::new",
        "timestamp=",
        "sign=",
        '"READY"',
        '"WARN"',
        '"BLOCKED"',
        "Performance baseline summary:",
        "Trend comparison:",
        "Performance baseline gate failed (FailOnWarn enabled).",
    ]

    missing = [token for token in required_tokens if token not in content]
    assert not missing, f"Missing expected script tokens: {missing}"
