"""add api import job fields

Revision ID: 93a5ad2e0df7
Revises: 0008_add_test_case_id
Create Date: 2026-03-29 11:46:13.211836

"""

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = '93a5ad2e0df7'
down_revision = '0008_add_test_case_id'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_project_created'), table_name='reports')
    op.drop_index(op.f('uq_reports_run_type'), table_name='reports')
    op.drop_table('reports')
    op.create_index(op.f('ix_ai_import_items_project_id'), 'ai_import_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_ai_import_items_tenant_id'), 'ai_import_items', ['tenant_id'], unique=False)
    op.add_column('ai_import_jobs', sa.Column('warnings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('ai_import_jobs', sa.Column('preview_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index(op.f('ix_ai_import_jobs_created_by'), 'ai_import_jobs', ['created_by'], unique=False)
    op.create_index(op.f('ix_ai_import_jobs_project_id'), 'ai_import_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_ai_import_jobs_tenant_id'), 'ai_import_jobs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_api_targets_created_by'), 'api_targets', ['created_by'], unique=False)
    op.create_index(op.f('ix_api_targets_project_id'), 'api_targets', ['project_id'], unique=False)
    op.create_index(op.f('ix_api_targets_tenant_id'), 'api_targets', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_testcase_bindings_created_by'), 'testcase_bindings', ['created_by'], unique=False)
    op.create_index(op.f('ix_testcase_bindings_project_id'), 'testcase_bindings', ['project_id'], unique=False)
    op.create_index(op.f('ix_testcase_bindings_tenant_id'), 'testcase_bindings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_testcase_bindings_testcase_id'), 'testcase_bindings', ['testcase_id'], unique=False)
    op.drop_index(op.f('ix_testcases_project_api_url'), table_name='testcases')
    op.drop_index(op.f('ix_testcases_project_feature'), table_name='testcases')
    op.drop_index(op.f('ix_testcases_project_story'), table_name='testcases')
    op.drop_index(op.f('uq_testcases_project_test_case_id'), table_name='testcases', postgresql_where='(test_case_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_testcases_project_test_case_id'), 'testcases', ['project_id', 'test_case_id'], unique=True, postgresql_where='(test_case_id IS NOT NULL)')
    op.create_index(op.f('ix_testcases_project_story'), 'testcases', ['project_id', 'story'], unique=False)
    op.create_index(op.f('ix_testcases_project_feature'), 'testcases', ['project_id', 'feature'], unique=False)
    op.create_index(op.f('ix_testcases_project_api_url'), 'testcases', ['project_id', 'api_url'], unique=False)
    op.drop_index(op.f('ix_testcase_bindings_testcase_id'), table_name='testcase_bindings')
    op.drop_index(op.f('ix_testcase_bindings_tenant_id'), table_name='testcase_bindings')
    op.drop_index(op.f('ix_testcase_bindings_project_id'), table_name='testcase_bindings')
    op.drop_index(op.f('ix_testcase_bindings_created_by'), table_name='testcase_bindings')
    op.drop_index(op.f('ix_api_targets_tenant_id'), table_name='api_targets')
    op.drop_index(op.f('ix_api_targets_project_id'), table_name='api_targets')
    op.drop_index(op.f('ix_api_targets_created_by'), table_name='api_targets')
    op.drop_index(op.f('ix_ai_import_jobs_tenant_id'), table_name='ai_import_jobs')
    op.drop_index(op.f('ix_ai_import_jobs_project_id'), table_name='ai_import_jobs')
    op.drop_index(op.f('ix_ai_import_jobs_created_by'), table_name='ai_import_jobs')
    op.drop_column('ai_import_jobs', 'preview_data_json')
    op.drop_column('ai_import_jobs', 'warnings_json')
    op.drop_index(op.f('ix_ai_import_items_tenant_id'), table_name='ai_import_items')
    op.drop_index(op.f('ix_ai_import_items_project_id'), table_name='ai_import_items')
    op.create_table('reports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('report_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('allure_result_key', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('allure_report_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("report_type::text = 'ALLURE'::text", name=op.f('reports_report_type_check')),
    sa.CheckConstraint("status::text = ANY (ARRAY['GENERATING'::character varying, 'READY'::character varying, 'FAILED'::character varying]::text[])", name=op.f('reports_status_check')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('reports_project_id_fkey')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('reports_run_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('reports_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reports_pkey'))
    )
    op.create_index(op.f('uq_reports_run_type'), 'reports', ['run_id', 'report_type'], unique=True)
    op.create_index(op.f('ix_reports_project_created'), 'reports', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###

